package com.example.MongoSpring.Model;

import lombok.Data;
import java.util.List;

@Data
public class Score

{

    private Integer holeNo;

    private Integer score;



    // Getters and setters can be generated by Lombok
    //ไว้ก่อนว่าอันไหนเก็บข้อมูลจำนวนมาก

}
